### PR TITLE
Add prefix for key maps

### PR DESCRIPTION
**Pull request by yylogo**

### CODE REVIEW

**Comment by fedorenchik** [comment]
Sorry, I don't understand, why this prefix is needed?

**Comment by inkarkat** [comment]
@fedorenchik The plugin has 11 default mappings. If you're generally okay with those, but want a prefix for all of them, this saves you from individually overriding those 11 mappings. The more you deviate from the suggested keys, the less configuration it saves.

I'm still on the fence about whether this is useful; thanks for providing another opinion on this ;-) I personally find the original mappings horrible, and have completely remapped everything. (But I have kept the original mappings so far for backward compatibility. Maybe I should offer my set of mappings as a secondary default?)

**Comment by fedorenchik** [comment]
@inkarkat Thanks for explanation.

**Comment by yylogo** [comment]
@inkarkat If don't set g:mwKeyMapPrefix, the key mappings are keep the default mappings.

**Comment by inkarkat** [comment]
I've instead chosen to list all default mappings in [the documentation](https://github.com/inkarkat/vim-mark/blob/379b04c5ea2d9f6ff5b0bb5bfe449f93dd70f45d/doc/mark.txt?plain=1#L477-L487), so that it's easy to copy-and-paste and adapt them according to personal tastes. After all, it's just 11 mappings, and this approach offers far more flexibility than a simple prefix (that doesn't even include the `<Leader>` part here). A prefix might work well if the suffix part is consistent and indisputable, but as I've mentioned before I don't like the default mappings at all and have personally remapped everything to make sense to me.

**Pull request closed without merging**
